var data1 = {
  'European Union': [
    ['Renewable energy', 40.8],
    ['Nuclear energy', 30.5],
    ['Solid fuels', 17.6],
    ['Natural gas', 7.2],
    ['Crude oil', 3.7],
    ['Other', 0.2],
  ],
  Belgium: [
    ['Renewable energy', 29.9],
    ['Nuclear energy', 62.8],
    ['Solid fuels', 4.8],
    ['Natural gas', 0.0],
    ['Crude oil', 0.0],
    ['Other', 2.4],
  ],
  Bulgaria: [
    ['Renewable energy', 23.8],
    ['Nuclear energy', 40.0],
    ['Solid fuels', 35.1],
    ['Natural gas', 0.4],
    ['Crude oil', 0.0],
    ['Other', 0.6],
  ],
  Czechia: [
    ['Renewable energy', 22.1],
    ['Nuclear energy', 31.9],
    ['Solid fuels', 44.9],
    ['Natural gas', 0.7],
    ['Crude oil', 0.4],
    ['Other', 0.1],
  ],
  Denmark: [
    ['Renewable energy', 45.6],
    ['Nuclear energy', 0.0],
    ['Solid fuels', 4.0],
    ['Natural gas', 12.5],
    ['Crude oil', 37.9],
    ['Other', 0.0],
  ],
  Germany: [
    ['Renewable energy', 47.5],
    ['Nuclear energy', 16.9],
    ['Solid fuels', 28.1],
    ['Natural gas', 4.1],
    ['Crude oil', 3.4],
    ['Other', 0.0],
  ],
  Estonia: [
    ['Renewable energy', 42.1],
    ['Nuclear energy', 0.0],
    ['Solid fuels', 57.9],
    ['Natural gas', 0.0],
    ['Crude oil', 0.0],
    ['Other', 0.0],
  ],
  Ireland: [
    ['Renewable energy', 45.5],
    ['Nuclear energy', 0.0],
    ['Solid fuels', 7.8],
    ['Natural gas', 46.7],
    ['Crude oil', 0.0],
    ['Other', 0.0],
  ],
  Greece: [
    ['Renewable energy', 64.8],
    ['Nuclear energy', 0.0],
    ['Solid fuels', 33.2],
    ['Natural gas', 0.1],
    ['Crude oil', 1.9],
    ['Other', 0.0],
  ],
  Spain: [
    ['Renewable energy', 55.4],
    ['Nuclear energy', 42.8],
    ['Solid fuels', 1.5],
    ['Natural gas', 0.1],
    ['Crude oil', 0.1],
    ['Other', 0.0],
  ],
  France: [
    ['Renewable energy', 22.8],
    ['Nuclear energy', 75.2],
    ['Solid fuels', 1.3],
    ['Natural gas', 0.0],
    ['Crude oil', 0.6],
    ['Other', 0.0],
  ],
  Croatia: [
    ['Renewable energy', 62.3],
    ['Nuclear energy', 0.0],
    ['Solid fuels', 1.0],
    ['Natural gas', 18.9],
    ['Crude oil', 17.7],
    ['Other', 0.0],
  ],
  Italy: [
    ['Renewable energy', 72.6],
    ['Nuclear energy', 0.0],
    ['Solid fuels', 3.2],
    ['Natural gas', 8.7],
    ['Crude oil', 15.5],
    ['Other', 0.0],
  ],
  Cyprus: [
    ['Renewable energy', 96.3],
    ['Nuclear energy', 0.0],
    ['Solid fuels', 3.7],
    ['Natural gas', 0.0],
    ['Crude oil', 0.0],
    ['Other', 0.0],
  ],
  Latvia: [
    ['Renewable energy', 99.3],
    ['Nuclear energy', 0.0],
    ['Solid fuels', 0.7],
    ['Natural gas', 0.0],
    ['Crude oil', 0.0],
    ['Other', 0.0],
  ],
  Lithuania: [
    ['Renewable energy', 83.9],
    ['Nuclear energy', 0.0],
    ['Solid fuels', 3.2],
    ['Natural gas', 0.0],
    ['Crude oil', 1.6],
    ['Other', 11.3],
  ],
  Luxembourg: [
    ['Renewable energy', 85.3],
    ['Nuclear energy', 0.0],
    ['Solid fuels', 14.7],
    ['Natural gas', 0.0],
    ['Crude oil', 0.0],
    ['Other', 0.0],
  ],
  Hungary: [
    ['Renewable energy', 29.3],
    ['Nuclear energy', 38.3],
    ['Solid fuels', 10.2],
    ['Natural gas', 12.5],
    ['Crude oil', 9.8],
    ['Other', 0.0],
  ],
  Malta: [
    ['Renewable energy', 100.0],
    ['Nuclear energy', 0.0],
    ['Solid fuels', 0.0],
    ['Natural gas', 0.0],
    ['Crude oil', 0.0],
    ['Other', 0.0],
  ],
  Netherlands: [
    ['Renewable energy', 26.0],
    ['Nuclear energy', 3.5],
    ['Solid fuels', 2.6],
    ['Natural gas', 62.9],
    ['Crude oil', 3.9],
    ['Other', 1.1],
  ],
  Austria: [
    ['Renewable energy', 84.9],
    ['Nuclear energy', 0.0],
    ['Solid fuels', 5.4],
    ['Natural gas', 5.1],
    ['Crude oil', 4.6],
    ['Other', 0.0],
  ],
  Poland: [
    ['Renewable energy', 21.6],
    ['Nuclear energy', 0.0],
    ['Solid fuels', 70.9],
    ['Natural gas', 5.8],
    ['Crude oil', 1.6],
    ['Other', 0.0],
  ],
  Portugal: [
    ['Renewable energy', 98.0],
    ['Nuclear energy', 0.0],
    ['Solid fuels', 2.0],
    ['Natural gas', 0.0],
    ['Crude oil', 0.0],
    ['Other', 0.0],
  ],
  Romania: [
    ['Renewable energy', 25.9],
    ['Nuclear energy', 12.9],
    ['Solid fuels', 12.8],
    ['Natural gas', 33.1],
    ['Crude oil', 15.3],
    ['Other', 0.0],
  ],
  Slovenia: [
    ['Renewable energy', 30.8],
    ['Nuclear energy', 42.7],
    ['Solid fuels', 26.3],
    ['Natural gas', 0.1],
    ['Crude oil', 0.0],
    ['Other', 0.0],
  ],
  Slovakia: [
    ['Renewable energy', 32.3],
    ['Nuclear energy', 59.8],
    ['Solid fuels', 7.0],
    ['Natural gas', 0.8],
    ['Crude oil', 0.1],
    ['Other', 0.0],
  ],
  Finland: [
    ['Renewable energy', 64.4],
    ['Nuclear energy', 30.1],
    ['Solid fuels', 4.7],
    ['Natural gas', 0.0],
    ['Crude oil', 0.0],
    ['Other', 0.8],
  ],
  Sweden: [
    ['Renewable energy', 62.8],
    ['Nuclear energy', 34.5],
    ['Solid fuels', 2.7],
    ['Natural gas', 0.0],
    ['Crude oil', 0.0],
    ['Other', 0.0],
  ],
  Iceland: [
    ['Renewable energy', 100.0],
    ['Nuclear energy', 0.0],
    ['Solid fuels', 0.0],
    ['Natural gas', 0.0],
    ['Crude oil', 0.0],
    ['Other', 0.0],
  ],
  Norway: [
    ['Renewable energy', 7.3],
    ['Nuclear energy', 0.0],
    ['Solid fuels', 0.1],
    ['Natural gas', 46.9],
    ['Crude oil', 45.6],
    ['Other', 0.1],
  ],
};

var data1colors = {
  'Renewable energy': '#50A832',
  'Nuclear energy': '#B93184',
  'Solid fuels': '#8E3F23',
  'Natural gas': '#F79416',
  'Crude oil': '#193769',
  'Other': '#C1C1C1'
}
